In [1]:
import gym_bandits
import gym
import numpy as np

from models import multi_armed_bandits

In [3]:
# Instantiate class:
env = gym.make("BanditTwoArmedHighLowFixed-v0")

mab = multi_armed_bandits.MultiArmedBandit(num_rounds=100,
                                           env=env)

### Epsilon Greedy

In [3]:
env = gym.make("BanditTwoArmedHighLowFixed-v0")

env.reset()

Q = mab.run_epsilon_greedy_learning(epsilon=.5)
display(Q)

/Users/janrathfelder/miniconda3/envs/gym/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:174: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.warn(
/Users/janrathfelder/miniconda3/envs/gym/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:187: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.warn(
/Users/janrathfelder/miniconda3/envs/gym/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:195: UserWarning: WARN: The result returned by `env.reset()` was not a tuple of the form `(obs, info)`, where `obs` is a observation and `info` is a dictionary containing additional information. Actual type: `<class 'int'>`
  logger.warn(
/Users/janrathfelder/miniconda3/envs/gym/lib/python3.8/site-packages/g

array([0.81944444, 0.17857143])

### Softmax

In [4]:
env = gym.make("BanditTwoArmedHighLowFixed-v0")

In [5]:
Q = mab.run_softmax_learning(T=50)
display(Q)

array([0.71186441, 0.12195122])

### UCB

In [6]:
env = gym.make("BanditTwoArmedHighLowFixed-v0")

In [7]:
Q = mab.run_ucb()
display(Q)

array([0.8, 0.1])

### Thompson Sampling

In [89]:
env = gym.make("BanditTwoArmedHighLowFixed-v0")

In [9]:
Q = mab.run_thompson_learning()
display(Q)

array([0.84042553, 0.33333333])